/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainUI;

import java.awt.*;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;

/**
 *
 * @author htvph
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    static int dashboardState = 0;
    static User currentUser;
    public Dashboard(User user) throws IOException {
        initComponents();
        
        // set up form's icon image
        Image i = ImageIO.read(getClass().getResource("/mainUI/targetlogo.png"));
        setIconImage(i);
        
        // puts form in center of screen
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        // sets greeting message on home page
        labelWelcome.setText("Welcome, " + user.getFirstName() + ".");
        
        // set dashboard state to 1
        // dashboardState keeps track of what screen the dashboard is on
        // 1 = home
        // 2 = grades
        // 3 = calendar
        // 4 = settings
        dashboardState = 1;
        this.currentUser = user;
        updateDashButtons();
        updateClassButtons();
        updateToDoList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelExit = new javax.swing.JPanel();
        labelExit = new javax.swing.JLabel();
        panelHomeButton = new javax.swing.JPanel();
        homeButton = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelHomeIcon = new javax.swing.JLabel();
        panelGradesButton = new javax.swing.JPanel();
        gradesButton = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labelGradesIcon = new javax.swing.JLabel();
        panelCalendarButton = new javax.swing.JPanel();
        calendarButton = new javax.swing.JPanel();
        labelCalendarIcon = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelSettingsButton = new javax.swing.JPanel();
        settingsButton = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        labelSettingsIcon = new javax.swing.JLabel();
        panelGrades = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        panelClass1 = new javax.swing.JPanel();
        buttonClass1 = new javax.swing.JPanel();
        labelClass1 = new javax.swing.JLabel();
        panelClass2 = new javax.swing.JPanel();
        buttonClass2 = new javax.swing.JPanel();
        labelClass2 = new javax.swing.JLabel();
        panelClass3 = new javax.swing.JPanel();
        buttonClass3 = new javax.swing.JPanel();
        labelClass3 = new javax.swing.JLabel();
        panelClass4 = new javax.swing.JPanel();
        buttonClass4 = new javax.swing.JPanel();
        labelClass4 = new javax.swing.JLabel();
        panelClass5 = new javax.swing.JPanel();
        buttonClass5 = new javax.swing.JPanel();
        labelClass5 = new javax.swing.JLabel();
        panelClass6 = new javax.swing.JPanel();
        buttonClass6 = new javax.swing.JPanel();
        labelClass6 = new javax.swing.JLabel();
        panelClass7 = new javax.swing.JPanel();
        buttonClass7 = new javax.swing.JPanel();
        labelClass7 = new javax.swing.JLabel();
        panelClass8 = new javax.swing.JPanel();
        buttonClass8 = new javax.swing.JPanel();
        labelClass8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listAssignments = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        listClassCategories = new javax.swing.JList();
        panelCalendar = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        labelToDoName1 = new javax.swing.JLabel();
        labelToDoName2 = new javax.swing.JLabel();
        labelToDoName3 = new javax.swing.JLabel();
        labelToDoName4 = new javax.swing.JLabel();
        labelToDoName5 = new javax.swing.JLabel();
        labelToDoName6 = new javax.swing.JLabel();
        labelToDoName7 = new javax.swing.JLabel();
        labelToDoName8 = new javax.swing.JLabel();
        checkBoxToDo1 = new javax.swing.JCheckBox();
        checkBoxToDo2 = new javax.swing.JCheckBox();
        checkBoxToDo3 = new javax.swing.JCheckBox();
        checkBoxToDo4 = new javax.swing.JCheckBox();
        checkBoxToDo5 = new javax.swing.JCheckBox();
        checkBoxToDo6 = new javax.swing.JCheckBox();
        checkBoxToDo7 = new javax.swing.JCheckBox();
        checkBoxToDo8 = new javax.swing.JCheckBox();
        textFieldTaskName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        panelNewTask = new javax.swing.JPanel();
        buttonNewTask = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panelHome = new javax.swing.JPanel();
        labelWelcome = new javax.swing.JLabel();
        panelSettings = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(700, 440));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelExit.setBackground(new java.awt.Color(0, 153, 153));
        panelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelExitMouseExited(evt);
            }
        });
        panelExit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelExit.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        labelExit.setForeground(new java.awt.Color(0, 0, 51));
        labelExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelExit.setText("X");
        labelExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelExitMouseExited(evt);
            }
        });
        panelExit.add(labelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        getContentPane().add(panelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 40, 40));

        panelHomeButton.setBackground(new java.awt.Color(0, 0, 51));
        panelHomeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelHomeButtonMouseEntered(evt);
            }
        });
        panelHomeButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeButton.setOpaque(false);
        homeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeButtonMouseExited(evt);
            }
        });
        homeButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelHomeButton.add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 110));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HOME");
        panelHomeButton.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 110, -1));

        labelHomeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainUI/Dashboard Icons/home.png"))); // NOI18N
        panelHomeButton.add(labelHomeIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 5, -1, -1));

        getContentPane().add(panelHomeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 110));

        panelGradesButton.setBackground(new java.awt.Color(0, 0, 51));
        panelGradesButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gradesButton.setOpaque(false);
        gradesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gradesButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gradesButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gradesButtonMouseExited(evt);
            }
        });
        gradesButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelGradesButton.add(gradesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 110));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("GRADES");
        panelGradesButton.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 110, -1));

        labelGradesIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainUI/Dashboard Icons/pencil.png"))); // NOI18N
        panelGradesButton.add(labelGradesIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        getContentPane().add(panelGradesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 110, 110));

        panelCalendarButton.setBackground(new java.awt.Color(0, 0, 51));
        panelCalendarButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        calendarButton.setOpaque(false);
        calendarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calendarButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                calendarButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                calendarButtonMouseExited(evt);
            }
        });
        calendarButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelCalendarButton.add(calendarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 110));

        labelCalendarIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainUI/Dashboard Icons/calendar.png"))); // NOI18N
        panelCalendarButton.add(labelCalendarIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 7, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TO-DO");
        panelCalendarButton.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 110, -1));

        getContentPane().add(panelCalendarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 110, 110));

        panelSettingsButton.setBackground(new java.awt.Color(0, 0, 51));
        panelSettingsButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        settingsButton.setOpaque(false);
        settingsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingsButtonMouseExited(evt);
            }
        });
        settingsButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelSettingsButton.add(settingsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 110));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("SETTINGS");
        panelSettingsButton.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 110, -1));

        labelSettingsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainUI/Dashboard Icons/settings.png"))); // NOI18N
        panelSettingsButton.add(labelSettingsIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 7, -1, -1));

        getContentPane().add(panelSettingsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 110, 110));

        panelGrades.setBackground(new java.awt.Color(0, 153, 153));
        panelGrades.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Grades");
        panelGrades.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        panelClass1.setBackground(new java.awt.Color(0, 0, 51));
        panelClass1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonClass1.setOpaque(false);
        buttonClass1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonClass1MouseClicked(evt);
            }
        });
        panelClass1.add(buttonClass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 40));

        labelClass1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        labelClass1.setForeground(new java.awt.Color(255, 255, 255));
        labelClass1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelClass1.setText("Class 1");
        panelClass1.add(labelClass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, -1));

        panelGrades.add(panelClass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 130, 40));

        panelClass2.setBackground(new java.awt.Color(0, 0, 51));
        panelClass2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonClass2.setOpaque(false);
        buttonClass2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonClass2MouseClicked(evt);
            }
        });
        panelClass2.add(buttonClass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 40));

        labelClass2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        labelClass2.setForeground(new java.awt.Color(255, 255, 255));
        labelClass2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelClass2.setText("Class 2");
        panelClass2.add(labelClass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, -1));

        panelGrades.add(panelClass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 130, 40));

        panelClass3.setBackground(new java.awt.Color(0, 0, 51));
        panelClass3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonClass3.setOpaque(false);
        buttonClass3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonClass3MouseClicked(evt);
            }
        });
        panelClass3.add(buttonClass3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 40));

        labelClass3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        labelClass3.setForeground(new java.awt.Color(255, 255, 255));
        labelClass3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelClass3.setText("Class 3");
        panelClass3.add(labelClass3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, -1));

        panelGrades.add(panelClass3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 130, 40));

        panelClass4.setBackground(new java.awt.Color(0, 0, 51));
        panelClass4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonClass4.setOpaque(false);
        buttonClass4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonClass4MouseClicked(evt);
            }
        });
        panelClass4.add(buttonClass4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 40));

        labelClass4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        labelClass4.setForeground(new java.awt.Color(255, 255, 255));
        labelClass4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelClass4.setText("Class 4");
        panelClass4.add(labelClass4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, -1));

        panelGrades.add(panelClass4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 130, 40));

        panelClass5.setBackground(new java.awt.Color(0, 0, 51));
        panelClass5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonClass5.setOpaque(false);
        buttonClass5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonClass5MouseClicked(evt);
            }
        });
        panelClass5.add(buttonClass5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 40));

        labelClass5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        labelClass5.setForeground(new java.awt.Color(255, 255, 255));
        labelClass5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelClass5.setText("Class 5");
        panelClass5.add(labelClass5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, -1));

        panelGrades.add(panelClass5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 130, 40));

        panelClass6.setBackground(new java.awt.Color(0, 0, 51));
        panelClass6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonClass6.setOpaque(false);
        buttonClass6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonClass6MouseClicked(evt);
            }
        });
        panelClass6.add(buttonClass6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 40));

        labelClass6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        labelClass6.setForeground(new java.awt.Color(255, 255, 255));
        labelClass6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelClass6.setText("Class 6");
        panelClass6.add(labelClass6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, -1));

        panelGrades.add(panelClass6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 130, 40));

        panelClass7.setBackground(new java.awt.Color(0, 0, 51));
        panelClass7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonClass7.setOpaque(false);
        buttonClass7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonClass7MouseClicked(evt);
            }
        });
        panelClass7.add(buttonClass7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 40));

        labelClass7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        labelClass7.setForeground(new java.awt.Color(255, 255, 255));
        labelClass7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelClass7.setText("Class 7");
        panelClass7.add(labelClass7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, -1));

        panelGrades.add(panelClass7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 130, 40));

        panelClass8.setBackground(new java.awt.Color(0, 0, 51));
        panelClass8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonClass8.setOpaque(false);
        buttonClass8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonClass8MouseClicked(evt);
            }
        });
        panelClass8.add(buttonClass8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 40));

        labelClass8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        labelClass8.setForeground(new java.awt.Color(255, 255, 255));
        labelClass8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelClass8.setText("Class 8");
        panelClass8.add(labelClass8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, -1));

        panelGrades.add(panelClass8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 130, 40));

        listAssignments.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listAssignments);

        panelGrades.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 200, -1));

        listClassCategories.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listClassCategories);

        panelGrades.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 200, -1));

        getContentPane().add(panelGrades, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 440));

        panelCalendar.setBackground(new java.awt.Color(0, 153, 153));
        panelCalendar.setForeground(new java.awt.Color(255, 255, 255));
        panelCalendar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelCalendar.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 200, 10));

        labelToDoName1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        labelToDoName1.setForeground(new java.awt.Color(255, 255, 255));
        labelToDoName1.setText("jLabel8");
        panelCalendar.add(labelToDoName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        labelToDoName2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        labelToDoName2.setForeground(new java.awt.Color(255, 255, 255));
        labelToDoName2.setText("jLabel8");
        panelCalendar.add(labelToDoName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        labelToDoName3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        labelToDoName3.setForeground(new java.awt.Color(255, 255, 255));
        labelToDoName3.setText("jLabel8");
        panelCalendar.add(labelToDoName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        labelToDoName4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        labelToDoName4.setForeground(new java.awt.Color(255, 255, 255));
        labelToDoName4.setText("jLabel8");
        panelCalendar.add(labelToDoName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        labelToDoName5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        labelToDoName5.setForeground(new java.awt.Color(255, 255, 255));
        labelToDoName5.setText("jLabel8");
        panelCalendar.add(labelToDoName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));

        labelToDoName6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        labelToDoName6.setForeground(new java.awt.Color(255, 255, 255));
        labelToDoName6.setText("jLabel8");
        panelCalendar.add(labelToDoName6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));

        labelToDoName7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        labelToDoName7.setForeground(new java.awt.Color(255, 255, 255));
        labelToDoName7.setText("jLabel8");
        panelCalendar.add(labelToDoName7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        labelToDoName8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        labelToDoName8.setForeground(new java.awt.Color(255, 255, 255));
        labelToDoName8.setText("jLabel8");
        panelCalendar.add(labelToDoName8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, -1, -1));

        checkBoxToDo1.setBackground(new java.awt.Color(0, 153, 153));
        checkBoxToDo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkBoxToDo1MouseClicked(evt);
            }
        });
        panelCalendar.add(checkBoxToDo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 92, -1, -1));

        checkBoxToDo2.setBackground(new java.awt.Color(0, 153, 153));
        checkBoxToDo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkBoxToDo2MouseClicked(evt);
            }
        });
        panelCalendar.add(checkBoxToDo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 132, -1, -1));

        checkBoxToDo3.setBackground(new java.awt.Color(0, 153, 153));
        checkBoxToDo3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkBoxToDo3MouseClicked(evt);
            }
        });
        panelCalendar.add(checkBoxToDo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 172, -1, -1));

        checkBoxToDo4.setBackground(new java.awt.Color(0, 153, 153));
        checkBoxToDo4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkBoxToDo4MouseClicked(evt);
            }
        });
        panelCalendar.add(checkBoxToDo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 212, -1, -1));

        checkBoxToDo5.setBackground(new java.awt.Color(0, 153, 153));
        checkBoxToDo5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkBoxToDo5MouseClicked(evt);
            }
        });
        panelCalendar.add(checkBoxToDo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 252, -1, -1));

        checkBoxToDo6.setBackground(new java.awt.Color(0, 153, 153));
        checkBoxToDo6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkBoxToDo6MouseClicked(evt);
            }
        });
        panelCalendar.add(checkBoxToDo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 292, -1, -1));

        checkBoxToDo7.setBackground(new java.awt.Color(0, 153, 153));
        checkBoxToDo7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkBoxToDo7MouseClicked(evt);
            }
        });
        panelCalendar.add(checkBoxToDo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 332, -1, -1));

        checkBoxToDo8.setBackground(new java.awt.Color(0, 153, 153));
        checkBoxToDo8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkBoxToDo8MouseClicked(evt);
            }
        });
        panelCalendar.add(checkBoxToDo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 372, -1, -1));

        textFieldTaskName.setBackground(new java.awt.Color(0, 153, 153));
        textFieldTaskName.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        textFieldTaskName.setForeground(new java.awt.Color(255, 255, 255));
        textFieldTaskName.setBorder(null);
        panelCalendar.add(textFieldTaskName, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 200, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("To-Do List");
        panelCalendar.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        panelNewTask.setBackground(new java.awt.Color(0, 0, 51));
        panelNewTask.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonNewTask.setOpaque(false);
        buttonNewTask.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonNewTaskMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonNewTaskMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonNewTaskMouseExited(evt);
            }
        });
        panelNewTask.add(buttonNewTask, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Add Task");
        panelNewTask.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 200, -1));

        panelCalendar.add(panelNewTask, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 200, 40));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("New Task");
        panelCalendar.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 200, -1));

        getContentPane().add(panelCalendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 440));

        panelHome.setBackground(new java.awt.Color(0, 153, 153));
        panelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelWelcome.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        labelWelcome.setForeground(new java.awt.Color(255, 255, 255));
        labelWelcome.setText("Welcome, name.");
        panelHome.add(labelWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        getContentPane().add(panelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 440));

        panelSettings.setBackground(new java.awt.Color(0, 153, 153));
        panelSettings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Settings");
        panelSettings.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        getContentPane().add(panelSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateDashButtons() {
        if(dashboardState == 1) {
            panelHomeButton.setBackground(new java.awt.Color(0,0,100));
            panelGradesButton.setBackground(new java.awt.Color(0,0,51));
            panelCalendarButton.setBackground(new java.awt.Color(0,0,51));
            panelSettingsButton.setBackground(new java.awt.Color(0,0,51));
            
            panelHome.setVisible(true);
            panelGrades.setVisible(false);
            panelCalendar.setVisible(false);
            panelSettings.setVisible(false);
        }
        else if(dashboardState == 2) {
            panelGradesButton.setBackground(new java.awt.Color(0,0,100));
            panelHomeButton.setBackground(new java.awt.Color(0,0,51));
            panelCalendarButton.setBackground(new java.awt.Color(0,0,51));
            panelSettingsButton.setBackground(new java.awt.Color(0,0,51));
            
            panelHome.setVisible(false);
            panelGrades.setVisible(true);
            panelCalendar.setVisible(false);
            panelSettings.setVisible(false);
        }
        else if(dashboardState == 3) {
            panelCalendarButton.setBackground(new java.awt.Color(0,0,100));
            panelHomeButton.setBackground(new java.awt.Color(0,0,51));
            panelGradesButton.setBackground(new java.awt.Color(0,0,51));
            panelSettingsButton.setBackground(new java.awt.Color(0,0,51));
            
            panelHome.setVisible(false);
            panelGrades.setVisible(false);
            panelCalendar.setVisible(true);
            panelSettings.setVisible(false);
        }
        else if (dashboardState == 4) {
            panelSettingsButton.setBackground(new java.awt.Color(0,0,100));
            panelHomeButton.setBackground(new java.awt.Color(0,0,51));
            panelGradesButton.setBackground(new java.awt.Color(0,0,51));
            panelCalendarButton.setBackground(new java.awt.Color(0,0,51));
            
            panelHome.setVisible(false);
            panelGrades.setVisible(false);
            panelCalendar.setVisible(false);
            panelSettings.setVisible(true);
        }
    }
    private void panelHomeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHomeButtonMouseEntered
        
    }//GEN-LAST:event_panelHomeButtonMouseEntered

    private void homeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseEntered
        // when hovered over home panel change color
        panelHomeButton.setBackground(new java.awt.Color(0,0,150));
    }//GEN-LAST:event_homeButtonMouseEntered

    private void homeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseExited
        // change back
        panelHomeButton.setBackground(new java.awt.Color(0,0,51));
        updateDashButtons();
    }//GEN-LAST:event_homeButtonMouseExited

    private void gradesButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gradesButtonMouseEntered
        // when hovered over grade panel change color
        panelGradesButton.setBackground(new java.awt.Color(0,0,150));
    }//GEN-LAST:event_gradesButtonMouseEntered

    private void gradesButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gradesButtonMouseExited
        // change back
        panelGradesButton.setBackground(new java.awt.Color(0,0,51));
        updateDashButtons();
    }//GEN-LAST:event_gradesButtonMouseExited

    private void calendarButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calendarButtonMouseEntered
        // when hovered over calendar panel change color
        panelCalendarButton.setBackground(new java.awt.Color(0,0,150));
    }//GEN-LAST:event_calendarButtonMouseEntered

    private void calendarButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calendarButtonMouseExited
        // change back
        panelCalendarButton.setBackground(new java.awt.Color(0,0,51));
        updateDashButtons();
    }//GEN-LAST:event_calendarButtonMouseExited

    private void labelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelExitMouseClicked
        // closes dashboard form when exit is clicked
        this.dispose();
        try {
            // returns to login
            new mainUI().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_labelExitMouseClicked

    private void labelExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelExitMouseEntered
        // change exit button to white when hovered
        labelExit.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_labelExitMouseEntered

    private void labelExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelExitMouseExited
        // changes color back to default when area is not hovered
        labelExit.setForeground(new java.awt.Color(0,0,51));
    }//GEN-LAST:event_labelExitMouseExited

    private void panelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelExitMouseClicked
        // closes login form when exit is clicked
        // this one is based on the panel which is larger and more forgiving to click
        this.dispose();
    }//GEN-LAST:event_panelExitMouseClicked

    private void panelExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelExitMouseEntered
        // change exit button to white when hovered
        labelExit.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_panelExitMouseEntered

    private void panelExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelExitMouseExited
        // changes color back to default when area is not hovered
        labelExit.setForeground(new java.awt.Color(0,0,51));
    }//GEN-LAST:event_panelExitMouseExited

    private void settingsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsButtonMouseEntered
        // when hovered over calendar panel change color
        panelSettingsButton.setBackground(new java.awt.Color(0,0,150));
    }//GEN-LAST:event_settingsButtonMouseEntered

    private void settingsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsButtonMouseExited
        // change back
        panelSettingsButton.setBackground(new java.awt.Color(0,0,51));
        updateDashButtons();
    }//GEN-LAST:event_settingsButtonMouseExited

    private void gradesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gradesButtonMouseClicked
        // grades tab selected
        dashboardState = 2;
        updateDashButtons();
        updateClassButtons();
    }//GEN-LAST:event_gradesButtonMouseClicked

    private void calendarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calendarButtonMouseClicked
        // calendar tab selected
        dashboardState = 3;
        updateDashButtons();
    }//GEN-LAST:event_calendarButtonMouseClicked

    private void homeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseClicked
        // home button clicked
        dashboardState = 1;
        updateDashButtons();
    }//GEN-LAST:event_homeButtonMouseClicked

    private void settingsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsButtonMouseClicked
        // settings button clicked
        dashboardState = 4;
        updateDashButtons();
    }//GEN-LAST:event_settingsButtonMouseClicked

    private void buttonNewTaskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonNewTaskMouseClicked
        currentUser.toDoList.add(new ToDo(textFieldTaskName.getText(), "", 0));
        textFieldTaskName.setText("");
        updateToDoList();
    }//GEN-LAST:event_buttonNewTaskMouseClicked

    private void buttonNewTaskMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonNewTaskMouseEntered
        panelNewTask.setBackground(new java.awt.Color(0, 0, 150));
    }//GEN-LAST:event_buttonNewTaskMouseEntered

    private void buttonNewTaskMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonNewTaskMouseExited
        panelNewTask.setBackground(new java.awt.Color(0, 0, 51));
    }//GEN-LAST:event_buttonNewTaskMouseExited

    private void checkBoxToDo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkBoxToDo1MouseClicked
        currentUser.toDoList.remove(0);
        updateToDoList();
    }//GEN-LAST:event_checkBoxToDo1MouseClicked

    private void checkBoxToDo2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkBoxToDo2MouseClicked
        currentUser.toDoList.remove(1);
        updateToDoList();
    }//GEN-LAST:event_checkBoxToDo2MouseClicked

    private void checkBoxToDo3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkBoxToDo3MouseClicked
        currentUser.toDoList.remove(2);
        updateToDoList();
    }//GEN-LAST:event_checkBoxToDo3MouseClicked

    private void checkBoxToDo4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkBoxToDo4MouseClicked
        currentUser.toDoList.remove(3);
        updateToDoList();
    }//GEN-LAST:event_checkBoxToDo4MouseClicked

    private void checkBoxToDo5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkBoxToDo5MouseClicked
        currentUser.toDoList.remove(4);
        updateToDoList();
    }//GEN-LAST:event_checkBoxToDo5MouseClicked

    private void checkBoxToDo6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkBoxToDo6MouseClicked
        currentUser.toDoList.remove(5);
        updateToDoList();
    }//GEN-LAST:event_checkBoxToDo6MouseClicked

    private void checkBoxToDo7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkBoxToDo7MouseClicked
        currentUser.toDoList.remove(6);
        updateToDoList();
    }//GEN-LAST:event_checkBoxToDo7MouseClicked

    private void checkBoxToDo8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkBoxToDo8MouseClicked
        currentUser.toDoList.remove(7);
        updateToDoList();
    }//GEN-LAST:event_checkBoxToDo8MouseClicked

    private void buttonClass1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonClass1MouseClicked
        if(currentUser.classes.isEmpty()) {
            try {
                new NewClass().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else {
            updateCategoriesLists(0);
        }
        
    }//GEN-LAST:event_buttonClass1MouseClicked

    private void buttonClass2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonClass2MouseClicked
        if(currentUser.classes.size() == 1) {
            try {
                new NewClass().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else {
            updateCategoriesLists(1);
        }
    }//GEN-LAST:event_buttonClass2MouseClicked

    private void buttonClass3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonClass3MouseClicked
        if(currentUser.classes.size() == 2) {
            try {
                new NewClass().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else {
            updateCategoriesLists(2);
        }
    }//GEN-LAST:event_buttonClass3MouseClicked

    private void buttonClass4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonClass4MouseClicked
        if(currentUser.classes.size() == 3) {
            try {
                new NewClass().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else {
            updateCategoriesLists(3);
        }
    }//GEN-LAST:event_buttonClass4MouseClicked

    private void buttonClass5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonClass5MouseClicked
        if(currentUser.classes.size() == 4) {
            try {
                new NewClass().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else {
            updateCategoriesLists(4);
        }
    }//GEN-LAST:event_buttonClass5MouseClicked

    private void buttonClass6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonClass6MouseClicked
        if(currentUser.classes.size() == 5) {
            try {
                new NewClass().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else {
            updateCategoriesLists(5);
        }
    }//GEN-LAST:event_buttonClass6MouseClicked

    private void buttonClass7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonClass7MouseClicked
        if(currentUser.classes.size() == 6) {
            try {
                new NewClass().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else {
            updateCategoriesLists(6);
        }
    }//GEN-LAST:event_buttonClass7MouseClicked

    private void buttonClass8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonClass8MouseClicked
        if(currentUser.classes.size() == 7) {
            try {
                new NewClass().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else {
            updateCategoriesLists(7);
        }
    }//GEN-LAST:event_buttonClass8MouseClicked
    
    public void updateCategoriesLists(int classIndex) {
        Vector <String> categoryNames = new Vector<String>();
        
        for(ClassCategory category : currentUser.classes.get(classIndex).getCategories()) {
            categoryNames.add(category.getName());
        }
        listClassCategories.setListData(categoryNames);
    }
    
    public void updateAssignmentLists() {
        Vector <String> assignmentNames = new Vector<String>();
        
        // TO DO update assignment list based on indices
                    
    }
    public void updateClassButtons() {
        buttonClass1.setVisible(false);
        buttonClass2.setVisible(false);
        buttonClass3.setVisible(false);
        buttonClass4.setVisible(false);
        buttonClass5.setVisible(false);
        buttonClass6.setVisible(false);
        buttonClass7.setVisible(false);
        buttonClass8.setVisible(false);
        
        labelClass1.setVisible(false);
        labelClass2.setVisible(false);
        labelClass3.setVisible(false);
        labelClass4.setVisible(false);
        labelClass5.setVisible(false);
        labelClass6.setVisible(false);
        labelClass7.setVisible(false);
        labelClass8.setVisible(false);
        
        panelClass1.setVisible(false);
        panelClass2.setVisible(false);
        panelClass3.setVisible(false);
        panelClass4.setVisible(false);
        panelClass5.setVisible(false);
        panelClass6.setVisible(false);
        panelClass7.setVisible(false);
        panelClass8.setVisible(false);
        
        if(currentUser.classes.isEmpty()) {
            // show button 1 as add new class
            buttonClass1.setVisible(true);
            labelClass1.setVisible(true);
            panelClass1.setVisible(true);
            labelClass1.setText("Add new class");
            panelClass1.setBackground(new java.awt.Color(150,0,0));
        }
        else if(currentUser.classes.size() == 1) {
            // show button 1 as class 1 and button 2 as add new class
            buttonClass1.setVisible(true);
            labelClass1.setVisible(true);
            panelClass1.setVisible(true);
            buttonClass2.setVisible(true);
            labelClass2.setVisible(true);
            panelClass2.setVisible(true);
            
            labelClass1.setText(currentUser.classes.get(0).getClassName());
            panelClass1.setBackground(new java.awt.Color(0,0,51));
            labelClass2.setText("Add new class");
            panelClass2.setBackground(new java.awt.Color(150,0,0));
        }
        else if (currentUser.classes.size() == 2) {
            // show buttons 1, 2 as classes 1, 2 and button 3 as add new class
            buttonClass1.setVisible(true);
            labelClass1.setVisible(true);
            panelClass1.setVisible(true);
            buttonClass2.setVisible(true);
            labelClass2.setVisible(true);
            panelClass2.setVisible(true);
            buttonClass3.setVisible(true);
            labelClass3.setVisible(true);
            panelClass3.setVisible(true);
            
            labelClass1.setText(currentUser.classes.get(0).getClassName());
            panelClass1.setBackground(new java.awt.Color(0,0,51));
            labelClass2.setText(currentUser.classes.get(1).getClassName());
            panelClass2.setBackground(new java.awt.Color(0,0,51));
            
            // button 3 will act as the new class button
            labelClass3.setText("Add new class");
            panelClass3.setBackground(new java.awt.Color(150,0,0));
        }
        else if (currentUser.classes.size() == 3) {
            // show buttons 1, 2, 3 as classes 1, 2, 3 and button 4 as add new class
            buttonClass1.setVisible(true);
            labelClass1.setVisible(true);
            panelClass1.setVisible(true);
            buttonClass2.setVisible(true);
            labelClass2.setVisible(true);
            panelClass2.setVisible(true);
            buttonClass3.setVisible(true);
            labelClass3.setVisible(true);
            panelClass3.setVisible(true);
            buttonClass4.setVisible(true);
            labelClass4.setVisible(true);
            panelClass4.setVisible(true);
            
            labelClass1.setText(currentUser.classes.get(0).getClassName());
            panelClass1.setBackground(new java.awt.Color(0,0,51));
            labelClass2.setText(currentUser.classes.get(1).getClassName());
            panelClass2.setBackground(new java.awt.Color(0,0,51));
            labelClass3.setText(currentUser.classes.get(2).getClassName());
            panelClass3.setBackground(new java.awt.Color(0,0,51));
            
            labelClass4.setText("Add new class");
            panelClass4.setBackground(new java.awt.Color(150,0,0));
        }
        else if(currentUser.classes.size() == 4) {
            buttonClass1.setVisible(true);
            labelClass1.setVisible(true);
            panelClass1.setVisible(true);
            buttonClass2.setVisible(true);
            labelClass2.setVisible(true);
            panelClass2.setVisible(true);
            buttonClass3.setVisible(true);
            labelClass3.setVisible(true);
            panelClass3.setVisible(true);
            buttonClass4.setVisible(true);
            labelClass4.setVisible(true);
            panelClass4.setVisible(true);
            labelClass5.setVisible(true);
            panelClass5.setVisible(true);
            
            labelClass1.setText(currentUser.classes.get(0).getClassName());
            panelClass1.setBackground(new java.awt.Color(0,0,51));
            labelClass2.setText(currentUser.classes.get(1).getClassName());
            panelClass2.setBackground(new java.awt.Color(0,0,51));
            labelClass3.setText(currentUser.classes.get(2).getClassName());
            panelClass3.setBackground(new java.awt.Color(0,0,51));
            labelClass4.setText(currentUser.classes.get(3).getClassName());
            panelClass4.setBackground(new java.awt.Color(0,0,51));
            
            labelClass5.setText("Add new class");
            panelClass5.setBackground(new java.awt.Color(150,0,0));
        }
        else if(currentUser.classes.size() == 5) {
            buttonClass1.setVisible(true);
            labelClass1.setVisible(true);
            panelClass1.setVisible(true);
            buttonClass2.setVisible(true);
            labelClass2.setVisible(true);
            panelClass2.setVisible(true);
            buttonClass3.setVisible(true);
            labelClass3.setVisible(true);
            panelClass3.setVisible(true);
            buttonClass4.setVisible(true);
            labelClass4.setVisible(true);
            panelClass4.setVisible(true);
            labelClass5.setVisible(true);
            panelClass5.setVisible(true);
            buttonClass6.setVisible(true);
            labelClass6.setVisible(true);
            panelClass6.setVisible(true);
            
            labelClass1.setText(currentUser.classes.get(0).getClassName());
            panelClass1.setBackground(new java.awt.Color(0,0,51));
            labelClass2.setText(currentUser.classes.get(1).getClassName());
            panelClass2.setBackground(new java.awt.Color(0,0,51));
            labelClass3.setText(currentUser.classes.get(2).getClassName());
            panelClass3.setBackground(new java.awt.Color(0,0,51));
            labelClass4.setText(currentUser.classes.get(3).getClassName());
            panelClass4.setBackground(new java.awt.Color(0,0,51));
            labelClass5.setText(currentUser.classes.get(4).getClassName());
            panelClass5.setBackground(new java.awt.Color(0,0,51));
            
            labelClass6.setText("Add new class");
            panelClass6.setBackground(new java.awt.Color(150,0,0));
        }
        else if(currentUser.classes.size() == 6) {
            buttonClass1.setVisible(true);
            labelClass1.setVisible(true);
            panelClass1.setVisible(true);
            buttonClass2.setVisible(true);
            labelClass2.setVisible(true);
            panelClass2.setVisible(true);
            buttonClass3.setVisible(true);
            labelClass3.setVisible(true);
            panelClass3.setVisible(true);
            buttonClass4.setVisible(true);
            labelClass4.setVisible(true);
            panelClass4.setVisible(true);
            labelClass5.setVisible(true);
            panelClass5.setVisible(true);
            buttonClass6.setVisible(true);
            labelClass6.setVisible(true);
            panelClass6.setVisible(true);
            buttonClass7.setVisible(true);
            labelClass7.setVisible(true);
            panelClass7.setVisible(true);
            
            labelClass1.setText(currentUser.classes.get(0).getClassName());
            panelClass1.setBackground(new java.awt.Color(0,0,51));
            labelClass2.setText(currentUser.classes.get(1).getClassName());
            panelClass2.setBackground(new java.awt.Color(0,0,51));
            labelClass3.setText(currentUser.classes.get(2).getClassName());
            panelClass3.setBackground(new java.awt.Color(0,0,51));
            labelClass4.setText(currentUser.classes.get(3).getClassName());
            panelClass4.setBackground(new java.awt.Color(0,0,51));
            labelClass5.setText(currentUser.classes.get(4).getClassName());
            panelClass5.setBackground(new java.awt.Color(0,0,51));
            labelClass6.setText(currentUser.classes.get(5).getClassName());
            panelClass6.setBackground(new java.awt.Color(0,0,51));
            
            labelClass7.setText("Add new class");
            panelClass7.setBackground(new java.awt.Color(150,0,0));
        }
        else if(currentUser.classes.size() == 7) {
            buttonClass1.setVisible(true);
            labelClass1.setVisible(true);
            panelClass1.setVisible(true);
            buttonClass2.setVisible(true);
            labelClass2.setVisible(true);
            panelClass2.setVisible(true);
            buttonClass3.setVisible(true);
            labelClass3.setVisible(true);
            panelClass3.setVisible(true);
            buttonClass4.setVisible(true);
            labelClass4.setVisible(true);
            panelClass4.setVisible(true);
            labelClass5.setVisible(true);
            panelClass5.setVisible(true);
            buttonClass6.setVisible(true);
            labelClass6.setVisible(true);
            panelClass6.setVisible(true);
            buttonClass7.setVisible(true);
            labelClass7.setVisible(true);
            panelClass7.setVisible(true);
            buttonClass8.setVisible(true);
            labelClass8.setVisible(true);
            panelClass8.setVisible(true);
            
            labelClass1.setText(currentUser.classes.get(0).getClassName());
            panelClass1.setBackground(new java.awt.Color(0,0,51));
            labelClass2.setText(currentUser.classes.get(1).getClassName());
            panelClass2.setBackground(new java.awt.Color(0,0,51));
            labelClass3.setText(currentUser.classes.get(2).getClassName());
            panelClass3.setBackground(new java.awt.Color(0,0,51));
            labelClass4.setText(currentUser.classes.get(3).getClassName());
            panelClass4.setBackground(new java.awt.Color(0,0,51));
            labelClass5.setText(currentUser.classes.get(4).getClassName());
            panelClass5.setBackground(new java.awt.Color(0,0,51));
            labelClass6.setText(currentUser.classes.get(5).getClassName());
            panelClass6.setBackground(new java.awt.Color(0,0,51));
            labelClass7.setText(currentUser.classes.get(6).getClassName());
            panelClass7.setBackground(new java.awt.Color(0,0,51));
            
            labelClass7.setText("Add new class");
            panelClass7.setBackground(new java.awt.Color(150,0,0));
        }
        else if(currentUser.classes.size() == 8) {
            buttonClass1.setVisible(true);
            labelClass1.setVisible(true);
            panelClass1.setVisible(true);
            buttonClass2.setVisible(true);
            labelClass2.setVisible(true);
            panelClass2.setVisible(true);
            buttonClass3.setVisible(true);
            labelClass3.setVisible(true);
            panelClass3.setVisible(true);
            buttonClass4.setVisible(true);
            labelClass4.setVisible(true);
            panelClass4.setVisible(true);
            labelClass5.setVisible(true);
            panelClass5.setVisible(true);
            buttonClass6.setVisible(true);
            labelClass6.setVisible(true);
            panelClass6.setVisible(true);
            buttonClass7.setVisible(true);
            labelClass7.setVisible(true);
            panelClass7.setVisible(true);
            buttonClass8.setVisible(true);
            labelClass8.setVisible(true);
            panelClass8.setVisible(true);
            
            labelClass1.setText(currentUser.classes.get(0).getClassName());
            panelClass1.setBackground(new java.awt.Color(0,0,51));
            labelClass2.setText(currentUser.classes.get(1).getClassName());
            panelClass2.setBackground(new java.awt.Color(0,0,51));
            labelClass3.setText(currentUser.classes.get(2).getClassName());
            panelClass3.setBackground(new java.awt.Color(0,0,51));
            labelClass4.setText(currentUser.classes.get(3).getClassName());
            panelClass4.setBackground(new java.awt.Color(0,0,51));
            labelClass5.setText(currentUser.classes.get(4).getClassName());
            panelClass5.setBackground(new java.awt.Color(0,0,51));
            labelClass6.setText(currentUser.classes.get(5).getClassName());
            panelClass6.setBackground(new java.awt.Color(0,0,51));
            labelClass7.setText(currentUser.classes.get(6).getClassName());
            panelClass7.setBackground(new java.awt.Color(0,0,51));
            labelClass8.setText(currentUser.classes.get(7).getClassName());
            panelClass8.setBackground(new java.awt.Color(0,0,51));
            
            // 8 is max number of classes
        }
    }
    private void updateToDoList() {
        
        checkBoxToDo1.setVisible(true);
        checkBoxToDo2.setVisible(true);
        checkBoxToDo3.setVisible(true);
        checkBoxToDo4.setVisible(true);
        checkBoxToDo5.setVisible(true);
        checkBoxToDo6.setVisible(true);
        checkBoxToDo7.setVisible(true);
        checkBoxToDo8.setVisible(true);
        
        checkBoxToDo1.setSelected(false);
        checkBoxToDo2.setSelected(false);
        checkBoxToDo3.setSelected(false);
        checkBoxToDo4.setSelected(false);
        checkBoxToDo5.setSelected(false);
        checkBoxToDo6.setSelected(false);
        checkBoxToDo7.setSelected(false);
        checkBoxToDo8.setSelected(false);
        
        labelToDoName1.setVisible(true);
        labelToDoName2.setVisible(true);
        labelToDoName3.setVisible(true);
        labelToDoName4.setVisible(true);
        labelToDoName5.setVisible(true);
        labelToDoName6.setVisible(true);
        labelToDoName7.setVisible(true);
        labelToDoName8.setVisible(true);
        
        if(currentUser.toDoList.isEmpty()) {
            checkBoxToDo1.setVisible(false);
            checkBoxToDo2.setVisible(false);
            checkBoxToDo3.setVisible(false);
            checkBoxToDo4.setVisible(false);
            checkBoxToDo5.setVisible(false);
            checkBoxToDo6.setVisible(false);
            checkBoxToDo7.setVisible(false);
            checkBoxToDo8.setVisible(false);
            
            labelToDoName1.setVisible(false);
            labelToDoName2.setVisible(false);
            labelToDoName3.setVisible(false);
            labelToDoName4.setVisible(false);
            labelToDoName5.setVisible(false);
            labelToDoName6.setVisible(false);
            labelToDoName7.setVisible(false);
            labelToDoName8.setVisible(false);
        }
        else if(currentUser.toDoList.size() == 1) {           
            checkBoxToDo2.setVisible(false);
            checkBoxToDo3.setVisible(false);
            checkBoxToDo4.setVisible(false);
            checkBoxToDo5.setVisible(false);
            checkBoxToDo6.setVisible(false);
            checkBoxToDo7.setVisible(false);
            checkBoxToDo8.setVisible(false);
            
            labelToDoName2.setVisible(false);
            labelToDoName3.setVisible(false);
            labelToDoName4.setVisible(false);
            labelToDoName5.setVisible(false);
            labelToDoName6.setVisible(false);
            labelToDoName7.setVisible(false);
            labelToDoName8.setVisible(false);
        }
        else if(currentUser.toDoList.size() == 2) {
            checkBoxToDo3.setVisible(false);
            checkBoxToDo4.setVisible(false);
            checkBoxToDo5.setVisible(false);
            checkBoxToDo6.setVisible(false);
            checkBoxToDo7.setVisible(false);
            checkBoxToDo8.setVisible(false);
            
            labelToDoName3.setVisible(false);
            labelToDoName4.setVisible(false);
            labelToDoName5.setVisible(false);
            labelToDoName6.setVisible(false);
            labelToDoName7.setVisible(false);
            labelToDoName8.setVisible(false);
        }
        else if(currentUser.toDoList.size() == 3) {
            checkBoxToDo4.setVisible(false);
            checkBoxToDo5.setVisible(false);
            checkBoxToDo6.setVisible(false);
            checkBoxToDo7.setVisible(false);
            checkBoxToDo8.setVisible(false);

            labelToDoName4.setVisible(false);
            labelToDoName5.setVisible(false);
            labelToDoName6.setVisible(false);
            labelToDoName7.setVisible(false);
            labelToDoName8.setVisible(false);
        }
        else if(currentUser.toDoList.size() == 4) {
            checkBoxToDo5.setVisible(false);
            checkBoxToDo6.setVisible(false);
            checkBoxToDo7.setVisible(false);
            checkBoxToDo8.setVisible(false);

            labelToDoName5.setVisible(false);
            labelToDoName6.setVisible(false);
            labelToDoName7.setVisible(false);
            labelToDoName8.setVisible(false);
        }
        else if(currentUser.toDoList.size() == 5) {
            checkBoxToDo6.setVisible(false);
            checkBoxToDo7.setVisible(false);
            checkBoxToDo8.setVisible(false);

            labelToDoName6.setVisible(false);
            labelToDoName7.setVisible(false);
            labelToDoName8.setVisible(false);
        }
        else if(currentUser.toDoList.size() == 6) {
            checkBoxToDo7.setVisible(false);
            checkBoxToDo8.setVisible(false);

            labelToDoName7.setVisible(false);
            labelToDoName8.setVisible(false);
        }
        else if(currentUser.toDoList.size() == 7) {
            checkBoxToDo8.setVisible(false);

            labelToDoName8.setVisible(false);
        }
        
        String[] toDoTasks = new String[8];
        for(int i = 0; i < currentUser.toDoList.size(); i++) {
            toDoTasks[i] = currentUser.toDoList.get(i).getName();
        }
        labelToDoName1.setText(toDoTasks[0]);
        labelToDoName2.setText(toDoTasks[1]);
        labelToDoName3.setText(toDoTasks[2]);
        labelToDoName4.setText(toDoTasks[3]);
        labelToDoName5.setText(toDoTasks[4]);
        labelToDoName6.setText(toDoTasks[5]);
        labelToDoName7.setText(toDoTasks[6]);
        labelToDoName8.setText(toDoTasks[7]);
        
        mainUI.saveUsers();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Dashboard(new User("", "", "", "", 0)).setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonClass1;
    private javax.swing.JPanel buttonClass2;
    private javax.swing.JPanel buttonClass3;
    private javax.swing.JPanel buttonClass4;
    private javax.swing.JPanel buttonClass5;
    private javax.swing.JPanel buttonClass6;
    private javax.swing.JPanel buttonClass7;
    private javax.swing.JPanel buttonClass8;
    private javax.swing.JPanel buttonNewTask;
    private javax.swing.JPanel calendarButton;
    private javax.swing.JCheckBox checkBoxToDo1;
    private javax.swing.JCheckBox checkBoxToDo2;
    private javax.swing.JCheckBox checkBoxToDo3;
    private javax.swing.JCheckBox checkBoxToDo4;
    private javax.swing.JCheckBox checkBoxToDo5;
    private javax.swing.JCheckBox checkBoxToDo6;
    private javax.swing.JCheckBox checkBoxToDo7;
    private javax.swing.JCheckBox checkBoxToDo8;
    private javax.swing.JPanel gradesButton;
    private javax.swing.JPanel homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelCalendarIcon;
    private javax.swing.JLabel labelClass1;
    private javax.swing.JLabel labelClass2;
    private javax.swing.JLabel labelClass3;
    private javax.swing.JLabel labelClass4;
    private javax.swing.JLabel labelClass5;
    private javax.swing.JLabel labelClass6;
    private javax.swing.JLabel labelClass7;
    private javax.swing.JLabel labelClass8;
    private javax.swing.JLabel labelExit;
    private javax.swing.JLabel labelGradesIcon;
    private javax.swing.JLabel labelHomeIcon;
    private javax.swing.JLabel labelSettingsIcon;
    private javax.swing.JLabel labelToDoName1;
    private javax.swing.JLabel labelToDoName2;
    private javax.swing.JLabel labelToDoName3;
    private javax.swing.JLabel labelToDoName4;
    private javax.swing.JLabel labelToDoName5;
    private javax.swing.JLabel labelToDoName6;
    private javax.swing.JLabel labelToDoName7;
    private javax.swing.JLabel labelToDoName8;
    private javax.swing.JLabel labelWelcome;
    private javax.swing.JList listAssignments;
    private javax.swing.JList listClassCategories;
    private javax.swing.JPanel panelCalendar;
    private javax.swing.JPanel panelCalendarButton;
    private javax.swing.JPanel panelClass1;
    private javax.swing.JPanel panelClass2;
    private javax.swing.JPanel panelClass3;
    private javax.swing.JPanel panelClass4;
    private javax.swing.JPanel panelClass5;
    private javax.swing.JPanel panelClass6;
    private javax.swing.JPanel panelClass7;
    private javax.swing.JPanel panelClass8;
    private javax.swing.JPanel panelExit;
    private javax.swing.JPanel panelGrades;
    private javax.swing.JPanel panelGradesButton;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelHomeButton;
    private javax.swing.JPanel panelNewTask;
    private javax.swing.JPanel panelSettings;
    private javax.swing.JPanel panelSettingsButton;
    private javax.swing.JPanel settingsButton;
    private javax.swing.JTextField textFieldTaskName;
    // End of variables declaration//GEN-END:variables
}
