/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainUI;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author htvph
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    
    String newUsername;
    String newPassword;
    
    public SignUp(String username, String password) throws IOException {
        initComponents();
        // set up form's icon image
        Image i = ImageIO.read(getClass().getResource("/mainUI/targetlogo.png"));
        setIconImage(i);
        
        // puts form in center of screen
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        this.newUsername = username;
        this.newPassword = password;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        textFieldFirstName = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        textFieldLastName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textFieldGrade = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        panelSignUp = new javax.swing.JPanel();
        labelSignUp = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(340, 280));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FIRST NAME");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 20));

        textFieldFirstName.setBackground(new java.awt.Color(0, 153, 153));
        textFieldFirstName.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        textFieldFirstName.setForeground(new java.awt.Color(255, 255, 255));
        textFieldFirstName.setBorder(null);
        textFieldFirstName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textFieldFirstNameMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textFieldFirstNameMouseExited(evt);
            }
        });
        textFieldFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldFirstNameActionPerformed(evt);
            }
        });
        jPanel1.add(textFieldFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 220, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 220, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 220, 10));

        textFieldLastName.setBackground(new java.awt.Color(0, 153, 153));
        textFieldLastName.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        textFieldLastName.setForeground(new java.awt.Color(255, 255, 255));
        textFieldLastName.setBorder(null);
        textFieldLastName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textFieldLastNameMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textFieldLastNameMouseExited(evt);
            }
        });
        textFieldLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldLastNameActionPerformed(evt);
            }
        });
        jPanel1.add(textFieldLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 220, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LAST NAME");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, 20));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("GRADE");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, 20));

        textFieldGrade.setBackground(new java.awt.Color(0, 153, 153));
        textFieldGrade.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        textFieldGrade.setForeground(new java.awt.Color(255, 255, 255));
        textFieldGrade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldGrade.setBorder(null);
        textFieldGrade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textFieldGradeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textFieldGradeMouseExited(evt);
            }
        });
        textFieldGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldGradeActionPerformed(evt);
            }
        });
        jPanel1.add(textFieldGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 50, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 50, 10));

        panelSignUp.setBackground(new java.awt.Color(0, 0, 51));
        panelSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSignUpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelSignUpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelSignUpMouseExited(evt);
            }
        });
        panelSignUp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelSignUp.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        labelSignUp.setForeground(new java.awt.Color(255, 255, 255));
        labelSignUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSignUp.setText("Sign Up");
        labelSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSignUpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelSignUpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelSignUpMouseExited(evt);
            }
        });
        panelSignUp.add(labelSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jPanel1.add(panelSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 100, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 340, 250));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tell us a little bit about yourself.");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 340, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Welcome to TargetGrade!");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 340, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldFirstNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFieldFirstNameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldFirstNameMouseClicked

    private void textFieldFirstNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFieldFirstNameMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldFirstNameMouseExited

    private void textFieldFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldFirstNameActionPerformed

    private void textFieldLastNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFieldLastNameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldLastNameMouseClicked

    private void textFieldLastNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFieldLastNameMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldLastNameMouseExited

    private void textFieldLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldLastNameActionPerformed

    private void textFieldGradeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFieldGradeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldGradeMouseClicked

    private void textFieldGradeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFieldGradeMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldGradeMouseExited

    private void textFieldGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldGradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldGradeActionPerformed

    // NEW ACCOUNT CREATED
    private void labelSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSignUpMouseClicked
        // create new user
        
        User newUser = new User(newUsername, newPassword, textFieldFirstName.getText(), textFieldLastName.getText(), Integer.parseInt(textFieldGrade.getText()), mainUI.savedUsers.size());
        // set new user in array
        // TO DO: Fix array because of change from array to arraylist
        mainUI.savedUsers.add(newUser);
        //TO DO: save the list of users in file
        mainUI.saveUsers();
        
        // close sign up form and open dashboard with new account
        try {            
            new Dashboard(newUser).setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_labelSignUpMouseClicked

    private void labelSignUpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSignUpMouseEntered
        // changes color of sign in button when hovered
        panelSignUp.setBackground(new java.awt.Color(0, 0, 120));
    }//GEN-LAST:event_labelSignUpMouseEntered

    private void labelSignUpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSignUpMouseExited
        // changes color back when mouse stops hovering
        panelSignUp.setBackground(new java.awt.Color(0, 0, 51));
    }//GEN-LAST:event_labelSignUpMouseExited

    private void panelSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSignUpMouseClicked
        
    }//GEN-LAST:event_panelSignUpMouseClicked

    private void panelSignUpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSignUpMouseEntered
        // changes color of sign in button when hovered
        //panelSignIn.setBackground(new java.awt.Color(0, 0, 120));
    }//GEN-LAST:event_panelSignUpMouseEntered

    private void panelSignUpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSignUpMouseExited
        // changes color back when mouse stops hovering
        //panelSignIn.setBackground(new java.awt.Color(0, 0, 51));
    }//GEN-LAST:event_panelSignUpMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new SignUp("","").setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel labelSignUp;
    private javax.swing.JPanel panelSignUp;
    private javax.swing.JTextField textFieldFirstName;
    private javax.swing.JTextField textFieldGrade;
    private javax.swing.JTextField textFieldLastName;
    // End of variables declaration//GEN-END:variables
}
